apiVersion: v1
kind: BuildConfig
metadata:
  name: ubi7-python3
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  source:
    dockerfile: "FROM registry.redhat.io/ubi7/python-36:latest"
  strategy:
    dockerStrategy:
      buildArgs:
        - name: tag
          value: ubi7-python3
  output:
    to:
      kind: ImageStreamTag
      name: ubi7-python3:latest
  triggers:
    - type: ImageChange
    - type: ConfigChange
